import config, { reactConfig } from '@iobroker/eslint-config';

export default [
    ...config,
    ...reactConfig,
    {
        languageOptions: {
            parserOptions: {
                projectService: {
                    allowDefaultProject: ['*.mjs'],
                },
                tsconfigRootDir: import.meta.dirname,
            },
        },
    },
    {
        ignores: [
            'src/assets/devices/parseNames.js',
            'src/assets/rooms/parseNames.js',
            // generated by "npm run icon-library"
            'src/Components/IconLibrary/iconLibraryData.ts',
            'tasks.ts',
            'tasksExample.ts',
        ],
    },
    {
        // disable temporary the rule 'jsdoc/require-param' and enable 'jsdoc/require-jsdoc'
        rules: {
            'jsdoc/require-jsdoc': 'off',
            'jsdoc/require-param': 'off',
            'react-hooks/set-state-in-effect': 'off'
        },
    },
];
